version: '2.1'
#docker-compose up
#docker exec -it dockerdeckjekyll_jekyll_1  /bin/bash
#jekyll new . --force
#jekyll build this builds the server for the first time.
#docker-compose
#this compose files creates errors 



    
services:
   jekyll:
     build: 
      context: ./docker/_build
     image: jekyll/jekyll:pages_deck
     env_file: 
       - docker/config.env     
     command: /usr/local/bin/deck-start.sh
     volumes:
       - ${JEKYLL_SOURCE:-jekyll_source}:/srv/jekyll
       - ${JEKYLL_SITE:-jekyll_site}:/srv/jekyll/_site 
     ports:
      - ${JEKYLL_PORT:-80}:4000
     restart: on-failure:2
volumes:
    jekyll_source:
    jekyll_site:        